.TH barprt 1 1-July-2001 "LIF Utilities" "LIF Utilities"
.SH NAME
barprt \- Display an HP41 barcode file (diagnostic)
.SH SYNOPSIS
.B barprt
.I < barcode_file
.SH DESCRIPTION
.B barprt
is a filter which reads an HP41 barcode file from standard input. For 
each logical record in the barcode file, the following is printed to 
standard output :
.TP
The number of bytes in that row of barcode
.TP 
The values of those bytes in hexadecimal
.TP
The values of those bytes in decimal
.PP
Standard output can, of course be redirected in the normal way if it 
is desired to pipe the output of 
.B barprt
to another program or store it in a file.
.PP
.B barprt
is intended as a diagnostic program for debugging barcode creation and 
printing programs. It can be used to ensure that the output of a barcode 
creation program is as expected. A barcode printing program can be tested 
by using it to print a barcode file and then comparing the output of 
.B barprt
applied to that file with the result of using the HP41 command 
.B WNDSCN
to read the corresponding row of printed barcode.
.SH REFERENCES
See 
.I barcode(5)
for details of the barcode file format
.SH EXAMPLES
If 
.I bar1 
is an HP41 barcode file then the command 
.PP
.B barprt < bar1
.PP
will display the contents of that file in human-readable form on the user's 
terminal 
.SH AUTHOR
.B barprt
was written by Tony Duell, ard@p850ug1.demon.co.uk and has been placed 
under the GNU Public License version 2.0
