.TH hx41rom 1  13-April-2018 "LIF Utilitites" "LIF Utilities"
.SH NAME
hx41rom \- a filter to convert a SDATA file which contains a scrambled (packed) ROM image written by the HEPAX WRTROM command to an unscrambled (unpacked) HP-41 ROM file.
.SH SYNOPSIS
.B hx41rom
.B <
.I Input file
.B >
.I Output file
.PP
.B hx41rom \-?
.SH DESCRIPTION
.B hx41rom
The HEPAX ROM can save HP-41 ROM images to a HP-IL mass storage. It creates
a SDATA file which contains 4 consecutive HP-41 10 bit ROM word in 5 bytes
of the file. A 4K ROM dump is thus stored in a 5120 byte file.
.PP
.B hx41rom
unscrambles such an raw SDATA file, storing each HP-41 10 bit word in 2 bytes of
the output file, and therefore a 4K image takes up 8192 bytes when
unscrambled. The resulting output file, although larger, is easier to
process with other programs.
.SH EXAMPLES
If
.I myrom.hx
is an SDATA file with the LIF header removed that contains the packed 
ROM image then
.PP
.B cat myrom.hx | hx41rom > myrom.rom
.PP 
will generate a file
.I myrom.rom
with the unpacked HP-41 rom image.
.SH AUTHOR
.B hx41rom
was written by Joachim Siebold, bug400@gmx.de using code from Tony Duell, 
ard@p850ug1.demon.co.uk and Christophe Gottheimer, cgh750@gmail.com and 
has been placed under the GNU Public License version 2.0
