.TH inp41 1 02-November-2024 "LIF Utilities" "LIF Utilities"
.SH NAME
inp41 \- a filter to decode a HP41 hexadecimal program
.SH SYNOPSIS
.B lifutils inp41 
<
.I Input device or file
>
.I Output_file
.PP
.B lifutils inp41
\-?
.PP
.SH DESCRIPTION
The HP41C Extended I/O Module contains 2 commands,
.I INP
and
.I OUTP
which translate HP41 programs (stored in the calculator's program memory) 
into a hexadecimal byte stream for transmission to other computers. 
.PP
.B inp41
reads such a hexadecimal file from standard input (which may be 
redirected from, for example, a serial port connected to the HP41 via an 
HP82164 RS232 interface), decodes it and writes the binary program to 
standard output. At the end of the transfer, the message 
.B checksum good
or
.B checksum bad
is written to standard error as appropriate.
.SH OPTIONS
.TP
.I \-?
Print a message giving the program usage to standard error.
.SH FILES
.I hardware/*
: Information on linking the HP41 to a PC.
.SH REFERENCES
The format of this hexadecimal stream is essentially undocumented and was 
discovered by experiment. The format is given in the comments at the 
start of the source file outp41.c
.SH AUTHOR
.B inp41
was written by Tony Duell, ard@p850ug1.demon.co.uk and has been placed 
under the GNU Public License version 2.0
