.TH lexcat71 03-November-2024 "LIF Utilitites" "LIF Utilities"
.SH NAME
lexcat71 \- display information about HP71 LEX files
.SH SYNOPSIS
.B lifutils lexcat71
[\-r]
.I INPUTFILE
[>
.I Output file
]
.PP
.B lifutils lexcat71
[\-r]
<
.I Input file
[>
.I Output file
]
.PP
.B lifutils lexcat71 \-?
.SH DESCRIPTION
.B lexcat71
reads a HP-71 LIF or raw lex file from standard input or the file specified by the command line parameter
.I INPUTFILE
and displays the following information on standard output:
.TP  4 
LEX file id
.TP  4 
for each of existing lex tables:
.PP
.IP \- 3  
lowest token ID
.IP \- 3  
highest token ID
.IP \- 3  
existence of speed table
.IP \- 3  
existence of message table
.IP \- 3  
existence of poll handler
.IP \- 3  
list of keywords with token number and characterization nibble
.SH OPTIONS
.TP
.I \-r
Skip an existing LIF header of the input file. This is mandatory, if the input file is a LIF instead of a raw file.
.TP
.I \-?
Print a message giving the program usage to standard error.
.SH REFERENCES
The LEX file format is documented in the 
.I HP\-71 IDS Volume 1, chapter 6.
.SH EXAMPLES
If
.I mem.lex
is a raw file containing an HP71 lex file, then
.PP
.B cat mem.lex | lifutils lexcat71
.PP 
will display information about the LEX file
.B mem.lex
.SH AUTHOR
.B lexcat71
was written by Joachim Siebold, bug400@gmx.de using code from Tony Duell, 
ard@p850ug1.demon.co.uk and has been placed 
under the GNU Public License version 2.0
