.TH lifdir 1 14-April-2018 "LIF Utilities" "LIF Utilities"
.SH NAME
lifdir \- print a directory of a LIF image file
.SH SYNOPSIS
.B lifdir [\-n] [\-v l]
.I <LIF image file>
.PP
.B lifdir \-?
.SH DESCRIPTION
.B lifdir
reads the directory of a LIF image file and prints 
its directory to standard output.
.PP
If the volume label is non\-blank, then this is printed first, followed 
by the date of formatting if this is valid. Each subsequent line contains 
the details of a single file, consisting of the file name, file type (see 
the 
.B FILE TYPE
section below), the number of bytes in the file and the total number of 
bytes occupied by the blocks of that file, and finally the file time and 
date stamp if this is valid.
.SH OPTIONS
.TP
.I \-n
Print file names only
.TP
.I \-v l
Verbosity level:
.RS
0: display file names only (same as -n)
.RE
.RS
1: default directory listing
.RE
.RS
2: extended directory listing including start sector, number of sectors occupied and implementation bytes
.RE
.TP
.I \-c
output all directory information as csv (comma is delimiter):
.RS
File name
.RE
.RS
File type (alphanumeric)
.RE
.RS
File type code (numeric)
.RE
.RS
File length
.RE
.RS
Start block
.RE
.RS
Number of blocks
.RE
.RS
Date: year, month, day
.RE
.RS
Time: hour, minutes, seconds
.RE
.RS
Implementation bytes 
.RE
.PP
.RS
Note: verbosity level and csv output options are mutually exclusive.
All numeric information is decimal.
.RE
.TP
.I \-?
Print a message giving the program usage to standard error.
.SH FILE TYPES
.B lifdir 
should recognise all file types of the Online LIF Disk project.
.PP
Unknown file types are printed as a 4\-digit hex number giving the value 
of the 2 file type bytes from the directory. See
.B lif_dir_utils.c
for details of the file types.
.SH EXAMPLES
If 
.I disk1.img
is a LIF disk image file then
.PP
.B lifdir  disk1.img
.PP
will print a directory listing of that image file.
.SH REFERENCES
The LIF disk directory format is documented in the
.I HP\-IL Interface Owners Manual for the HP\-71 (Hewlett\-Packard)
with further details (particularly HP\-41 and HP\-75 file types) in the 
.I HP\-41 Synthetic Quick Reference Guide (Jeremy Smith)
.SH BUGS
Not all file types have been tested.
.SH AUTHOR
.B lifdir
was written by Tony Duell, ard@p850ug1.demon.co.uk and has been placed 
under the GNU Public License version 2.0
