.TH lifilper 1 26-Oct-2014 "LIF Utilities" "LIF Utilities"
.SH NAME
lifilper \- emulate HPIL disk drive and display for the PIL-Box
.SH SYNOPSIS
.B lifilper [\-n] [\-s] [\-d] 
.I <LIF image file>
.I <PIL-Box tty>
.I <scope file>
.PP
.B lifilper \-?
.SH DESCRIPTION
.B lifilper
emulates a HPIL disk drive and display for the PIL-Box (J-F Garnier).
.PP
The LIF image file is only opened when a mass storage operation is performed. Otherwise the LIF image file can be modified while lifilper is running.
.SH OPTIONS
.TP
.I \-c
Emulate a HP 82161 cassette medium, otherwise a HP 9114A disk medium is
emulated.
.TP
.I \-d
Emulate a HP-IL display device
.TP
.I \-s
Output HP-IL mnemonics
.TP
.I \-?
Print a message giving the program usage to standard error.
.PP
Note: the \-d and the \-s option are mutually exclusive.
.SH EXAMPLES
If 
.I disk1.lif
is a LIF disk image file and the PIL-Box is connected to
.I /dev/ttyUSB0
then
.PP
.B lifilper  disk1.lif /dev/ttyUSB0
.PP
will emulate disk1.lif as a HP8114A disk
.SH REFERENCES
The LIF disk directory format is documented in the
.I HP\-IL Interface Owners Manual for the HP\-71 (Hewlett\-Packard)
with further details (particularly HP41 and HP75 file types) in the 
.I HP\-41 Synthetic Quick Reference Guide (Jeremy Smith)
.SH AUTHOR
.B lifilper
uses code of the
.I liftool
software writted by  Christophe Gottheimer, cgh75015@gmail.com and
was modified by Joachim Siebold, bug400@gmx.de
