.TH liflabel 1 16-March-2019 "LIF Utilities" "LIF Utilities"
.SH NAME
liflabel \- label a LIF image file
.SH SYNOPSIS
.B liflabel
[\-c] [\-p]
.I <LIF image file> <Label name>
.PP
.B liflabel \-?
.SH DESCRIPTION
.B liflabel
sets the label in the volume header of the file specified by
.I LIF image file
to the label specified by
.I Label name
.SH OPTIONS
.TP
.I \-c
Clears an existing label
.TP
.I \-p
Label a LIF file system on a floppy disk. Note: this option is only supported on LINUX. Specify the floppy device instead of the lif-image-filename. See the LIFUTILS tutorial for details.
.TP
.I \-?
Print a message giving the program usage to standard error.
.SH EXAMPLES
If 
.I disk1.dat
is a LIF image file then
.PP
.B liflabel disk1.dat TEST1
.PP
will set the label of the LIF image file
.I disk1.dat
to
.I TEST1
.PP
.B liflabel -c disk1.dat
.PP
will clear an existing label on the LIF image file 
.I disk1.dat
.SH REFERENCES
The LIF disk format is documented in the
.I HP\-IL Interface Owners Manual for the HP\-71 (Hewlett\-Packard)
with further details (particularly HP41 and HP75 file types) in the 
.I HP\-41 Synthetic Quick Reference Guide (Jeremy Smith)
.SH AUTHOR
.B liflabel
was written by Joachim Siebold, bug400@gmx.de  using code from Tony Duell, 
ard@p850ug1.demon.co.uk and has been placed under the GNU Public 
License version 2.0
