.TH liflabel 1 14-April-2018 "LIF Utilities" "LIF Utilities"
.SH NAME
liflabel \- label a LIF image file
.SH SYNOPSIS
.B liflabel
[\-c] 
.I <LIF image file> <Label name>
.PP
.B liflabel \-?
.SH DESCRIPTION
.B liflabel
sets the label in the volume header of the file specified by
.I LIF image file
to the label specified by
.I Label name
.SH OPTIONS
.TP
.I \-c
Clears an existing label
.TP
.I \-?
Print a message giving the program usage to standard error.
.SH EXAMPLES
If 
.I disk1.img
is a LIF image file then
.PP
.B liflabel disk1.img TEST1
.PP
will set the label of the LIF image file
.I disk1.img
to
.I TEST1
.PP
.B liflabel -c disk1.img
.PP
will clear an existing label on the LIF image file 
.I disk1.img
.SH REFERENCES
The LIF disk format is documented in the
.I HP\-IL Interface Owners Manual for the HP\-71 (Hewlett\-Packard)
with further details (particularly HP41 and HP75 file types) in the 
.I HP\-41 Synthetic Quick Reference Guide (Jeremy Smith)
.SH AUTHOR
.B liflabel
was written by Joachim Siebold, bug400@gmx.de  using code from Tony Duell, 
ard@p850ug1.demon.co.uk and has been placed under the GNU Public 
License version 2.0
