.TH lifpack 1 04-November-2024 "LIF Utilities" "LIF Utilities"
.SH NAME
lifpack \- pack a LIF image file
.SH SYNOPSIS
.B lifutils lifpack 
[\-p]
.I LIFIMAGE
.PP
.B lifutils lifpack \-?
.SH DESCRIPTION
.B lifpack
packs the directory and the file area of the LIF image file specifed by
.I LIFIMAGE. 
After packing all unused sectors of the file area are available in one contiguous block. All directory entries are allocated at the beginning of the directory area which speeds up directory searches.
.SH OPTIONS
.TP
.I \-p
Pack a LIF file system on a floppy disk. Note: this option is only supported on LINUX. Specify the floppy device instead of the lif-image-filename. See the LIFUTILS tutorial for details.
.TP
.I \-?
Print a message giving the program usage to standard error.
.SH EXAMPLES
If 
.I disk1.dat
is a LIF image file then
.PP
.B lifutils lifpack  disk1.dat
.PP
will pack the lif disk image file
.I disk1.dat.
.B
Note:
the packed LIF image file will be truncated to the
last sector that is used by the packed file area.
.SH REFERENCES
The LIF disk format is documented in the
.I HP\-IL Interface Owners Manual for the HP\-71 (Hewlett\-Packard)
with further details (particularly HP41 and HP75 file types) in the 
.I HP\-41 Synthetic Quick Reference Guide (Jeremy Smith)
.SH AUTHOR
.B lifpack
was written by Joachim Siebold, bug400@gmx.de  using code from Tony Duell, 
ard@p850ug1.demon.co.uk and has been placed under the GNU Public 
License version 2.0
