.TH lifraw 1 14-April-2018 "LIF Utilitites" "LIF Utilities"
.SH NAME
lifraw \- remove the LIF file header from a LIF file
.SH SYNOPSIS
.B lifutils lifraw
.I INPUTFILE
>
.I Output file
.PP
.B lifutils lifraw
<
.I Input file
>
.I Output file
.PP
.B lifutils lifraw \-?
.SH DESCRIPTION
.B lifraw
removes the 32 byte LIF header from a LIF file which is either read from
.I INPUTFILE
or standard input.
.SH OPTIONS
.I \-?
Print a message giving the program usage to standard error.
.SH REFERENCES
The LIF disk directory format is documented in the
.I HP\-IL Interface Owners Manual for the HP\-71 (Hewlett\-Packard)
with further details (particularly HP41 and HP75 file types) in the 
.I HP\-41 Synthetic Quick Reference Guide (Jeremy Smith)
.SH EXAMPLES
If
.I zline.p41
is a LIF file containing an HP41 program then
.PP
.B cat zline.p41 | lifutils lifraw \> zline.raw
.PP 
will generate a raw file 
.B zline.raw
.SH AUTHOR
.B lifraw
was written by Joachim Siebold, bug400@gmx.de using code from Tony Duell, 
ard@p850ug1.demon.co.uk and has been placed 
under the GNU Public License version 2.0
