.TH liftext75 1 05-November-2024 "LIF Utilities" "LIF Utilities"
.SH NAME 
liftext75 \- translate a raw HP-75 text file into an ASCII file
.SH SYNOPSIS
.B lifutils liftext75
[\-n][\-r]
.I INPUTFILE 
[>
.I Output file
]
.PP
.B lifutils liftext75
[\-n][\-r]
<
.I Input file
[>
.I Output file
]
.PP
.B lifutils liftext75 \-?
.SH DESCRIPTION
.B liftext75
translates a LIF or raw HP75 text file into an ASCII file.
One logical line of the input file is translated to one line of output,
terminated by a newline.  The HP75 text file is read from standard input or the file
.I INPUTFILE
and the plain ASCII equivalent is written to standard output.
.SH OPTIONS
.TP
.I \-n 
Print a decimal line number at the start of each output line.
.TP
.I \-r
Skip an existing LIF header of the input file. This is mandatory, if the input file is a LIF instead of a raw file.
.TP
.I \-?
Print a message giving usage to standard error.
.SH EXAMPLES
If
.I disk1.dat
is a LIF image file containing an HP75 text file called 
.I T75
then
.PP
.B lifutils lifget \-r disk1.dat T75 | lifutils liftext75
.PP 
will list that file to standard output.
.SH AUTHOR
.B liftext75
was written by Tony Duell, ard@p850ug1.demon.co.uk and has been placed 
under the GNU Public License version 2.0
