.TH liftext 1 14-April-2018 "LIF Utilities" "LIF Utilities"
.SH NAME
liftext \- a filter to translate an HP LIF text file into an ASCII text file
.SH SYNOPSIS
.B liftext 
.B <
.I Input file
.B >
.I Output file
.SH DESCRIPTION
.B liftext
is a filter that reads an HP LIF text file (also known as a LIF1 format file) 
from standard input and writes the equivalent standard text file to 
standard output. Each record of the HP text file is assumed to be one 
line of the output file. This file type is used on the HP-71 (TEXT) and
the extended memory or HEPAX file system of the HP-41 (ASCII).
.PP
.B
Note:
.I
liftext
does not perform any character set conversions.

.SH REFERENCES
The HP text file format is documented in section 11.2.8.1 of the 
.I HP-71 Software Internal Design Specifications Volume 1 (Hewlett\-Packard)
.SH EXAMPLES
If 
.I disk1.dat
is a LIF disk image containing an HP text file called 
.I TEXTA 
then
.PP
.B lifget -r disk1.dat TEXTA | liftext
.PP 
will produce a listing of this file to standard output.
.SH AUTHOR
.B liftext
was written by Tony Duell, ard@p850ug1.demon.co.uk and has been placed 
under the GNU Public License version 2.0
