.TH lifversion 1 10-October-2017 "LIF Utilitites" "LIF Utilities"
.SH NAME
lifversion \- display the version of the LIF Utilities
.SH SYNOPSIS
.B lifversion
.SH DESCRIPTION
.B lifversion
writes the version number of the LIF Utilities to standard output.
.B lifversion
was written by Joachim Siebold, bug400@gmx.de and has been placed 
under the GNU Public License version 2.0
