.TH prog41bar 1 05-November-2024 "LIF Utilities" "LIF Utilities"
.SH NAME
prog41bar \- convert a HP-41 program raw file into an intermediate barcode file
.SH SYNOPSIS
.B lifutils prog41bar 
[\-r]
.I INPUTFILE
.B >
.I Output file
.PP
.B lifutils prog41bar 
[\-r]
<
.I Input file
.B >
.I Output file
.PP
.B lifutils prog41bar -?
.SH DESCRIPTION
.B prog41bar
is a program that reads a HP-41 program raw file from standard input or the file specified by the parameter 
.I INPUTFILE
and writes the corresponding intermediate barcode file to standard output. 
.PP
The output of 
.B prog41bar
can be piped to a suitable barcode printing program such as 
.B barps
.SH OPTIONS
.TP
.I \-r
Skip an existing LIF header of the input file. This is mandatory, if the input file is a LIF instead of a raw file.
.TP
.I \-?
Print a message giving the program usage to standard error.
.SH REFERENCES
The format of HP41 barcode is given in the book
.I Creating your own HP41 Barcode (Hewlett\-Packard)
.PP
The format of the intermediate barcode file written by sdatabar is given in 
.I barcode(5)
.SH EXAMPLES
If
.I prog1.raw
is a HP-41 program raw file and 
.I postscript
is a postscript printer
then
.PP
.B lifutils prog41bar < prog1.raw | lifutils barps 'Program 1' | lpr -P postscript
.PP
will print that file as HP-41 barcode on the postscript printer.
.SH AUTHOR
.B prog41bar
was written by Tony Duell, ard@p850ug1.demon.co.uk, and has been placed 
under the GNU Public License version 2.0
