.TH rom41hx 1 24-March-2014 "LIF Utilitites" "LIF Utilities"
.SH NAME
rom41hx \- a filter to convert a HP-41 rom file to a data file that can be uploaded to HEPAX RAM with the READROM command
.SH SYNOPSIS
.B rom41hx
.I <LIF filename>
.B <
.I Input file
.B >
.I Output file
.PP
.B rom41hx \-?
.SH DESCRIPTION
.B rom41hx
is a filter which generates a  LIF data file from a HP41 rom file.
The filter reads the rom data from standard input and writes the LIF 
file header and the rom data in scrambled hepax format 
 to standard output. Note: this filter adjusts an incorrect ROM checksum.
.SH EXAMPLES
If
.I HPILDv1B.ROM 
is the rom file of the HP-IL development module then
.PP
.B cat HPILDv1B.ROM | rom41hx HPILDEV \> hpildev.sda
.PP 
will generate a LIF file 
.I hpildvev.sda
with the LIF filename
.I HPILDEV
.SH AUTHOR
.B rom41hx
was written by Joachim Siebold, bug400@gmx.de using code from Tony Duell, 
ard@p850ug1.demon.co.uk and Christophe Gottheimer, cgh750@gmail.com and 
has been placed under the GNU Public License version 2.0
