.TH rom41lif 1 01-November-2024 "LIF Utilitites" "LIF Utilities"
.SH NAME
rom41lif \- convert a HP-41 rom file to a LIF file of type sdata 
.SH SYNOPSIS
.B lifutils rom41lif
.I LIFFILENAME
.I INPUTFILE
> 
.I Output file
.PP
.B lifutils rom41lif
.I LIFFILENAME
< 
.I Input file 
> 
.I Output file
.PP
.B lifutils rom41lif \-?
.PP
.SH DESCRIPTION
.B rom41lif
generates a LIF sdata file from an HP41 rom file.
The program reads the rom data from standard input or the file specified by the command line paramter
.I INPUTFILE
and writes the LIF file header and the uncompressed rom data to standard output. 
Note: this program updates incorrect ROM checksums.
.SH OPTIONS
.TP
.I \-?
Print a message giving the program usage to standard error.
.SH EXAMPLES
If
.I HPILDv1B.ROM 
is the rom file of the HP-IL development module then
.PP
.B cat HPILDv1B.ROM | lifutils rom41lif HPILDEV | lifutils lifput lifimage.dat
.PP
will put the sdata rom file with the name
.I HPILDEV
into the LIF image file
.I lifimage.dat
.SH AUTHOR
.B rom41lif
was written by Joachim Siebold, bug400@gmx.de using code from Tony Duell, 
ard@p850ug1.demon.co.uk and has been placed under the GNU Public License 
version 2.0.
