.TH rom41lif 1 14-April-2018 "LIF Utilitites" "LIF Utilities"
.SH NAME
rom41lif \- a filter to convert a HP-41 rom file to a LIF file of type sdata that can be used to update the HP-41 CL 
.SH SYNOPSIS
.B rom41lif
.I <LIF filename>
.B <
.I Input file
.B >
.I Output file
.PP
.SH DESCRIPTION
.B rom41lif
is a filter which generates a LIF sdata file from an HP41 rom file.
The filter reads the rom data from standard input and writes the LIF 
file header and the uncompressed rom data to standard output. 
Note: this filter updates incorrect ROM checksums.

.SH EXAMPLES
If
.I HPILDv1B.ROM 
is the rom file of the HP-IL development module then
.PP
.B cat HPILDv1B.ROM | rom41lif HPILDEV | lifput lifimage.dat
.PP
will put the sdata rom file with the name
.I HPILDEV
into the LIF image file
.I lifimage.dat
.SH AUTHOR
.B rom41lif
was written by Joachim Siebold, bug400@gmx.de using code from Tony Duell, 
ard@p850ug1.demon.co.uk and has been placed under the GNU Public License 
version 2.0.
