.TH textlif 1 14-April-2018 "LIF Utilitites" "LIF Utilities"
.SH NAME
textlif \- a filter to convert an ASCII file to a LIF text file
.SH SYNOPSIS
.B textlif
[\-r registers]
.I <LIF filename>
.B <
.I Input file
.B >
.I Output file
.PP
.B textlif \-?
.SH DESCRIPTION
.B textlif
is a filter which generates a LIF file from a text file.
The filter reads the text from standard
input and writes the LIF file header and the LIF formatted text to
standard output. This file type can be used on the HP-71 (TEXT) or
the HP-41 extended Memory or HEPAX file system (ASCII). If the file
shall be used on a HP-41 the \-r option is mandatory.
.SH OPTIONS
.TP
.I \-r
This option specifies the file size in registers which shall be allocated 
for the resulting file in the HP-41 extended memory or the HEPAX file system. 
If a value of 0 is specified the number of register is determined from the 
size of the input text file.  According to the HEPAX documentation the 
maximum file size is 577 registers.
.TP
.I \-?
Print a message giving the program usage to standard error.
.SH REFERENCES
The HP text file format is documented in section 11.2.8.1 of the 
.I
HP71 Software Internal Design Specifications Volume 1 (Hewlett-Packard)
.SH EXAMPLES
If
.I demo.txt
is an ASCII text file 
then
.PP
.B cat demo.txt | textlif DEMO | lifput lifimage.img
.PP
will put the LIF text file with the name
.I DEMO
into the LIF image file
.I lifimage.img
.SH AUTHOR
.B textlif
was written by Joachim Siebold, bug400@gmx.de using code from Tony Duell, 
ard@p850ug1.demon.co.uk and has been placed 
under the GNU Public License version 2.0
