#!/bin/bash
# copy files from a LIF image file to another
if test $# -ne 2 -a  $# -ne 3 
then
   echo "Usage: lifcopy lif-image-filename1 lif-image-filename2 [Pattern]"
   exit
fi
if  test ! -r "${1}"
then
   echo "No input file specified"
   exit
fi
if test ! -r "${2}"
then
   echo "No output file specified"
   exit
fi
if test $# -eq 2
then
   for i in `lifdir -n ${1}`; do lifget -d ${1} ${i} | lifput ${2}; done
fi
if test $# -eq 3
then
   for i in `lifdir -n ${1} | grep "${3}"`; do lifget -d ${1} ${i} | lifput ${2}; done
fi

